"use client";

import { Suspense, useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { ShieldCheck, ShieldX, Search, Loader2, ArrowLeft } from "lucide-react";
import { Card } from "@/components/ui/card";
import { PageHeader } from "@/components/ui/page-header";
import { apiGet } from "@/lib/api";

interface SignatureRecord {
  id: string;
  verifyId: string;
  signature: string;
  reportId: string;
  reportName: string;
  category: string;
  period: string;
  records: number;
  generatedAt: string;
  generatedBy: string;
}

type Result = { status: "authentic"; record: SignatureRecord } | { status: "invalid" } | null;

function VerifyInner() {
  const searchParams = useSearchParams();
  const [code, setCode] = useState("");
  const [checking, setChecking] = useState(false);
  const [result, setResult] = useState<Result>(null);

  const runVerify = useCallback(async (raw: string) => {
    const q = raw.trim().toUpperCase();
    if (!q) return;
    setChecking(true);
    setResult(null);
    try {
      const res = await apiGet<{ items: SignatureRecord[] }>("/api/collections/report-signatures", { limit: 500 });
      const match = res.items.find((r) => (r.verifyId ?? "").toUpperCase() === q);
      setResult(match ? { status: "authentic", record: match } : { status: "invalid" });
    } catch {
      setResult({ status: "invalid" });
    } finally {
      setChecking(false);
    }
  }, []);

  // One-scan verification: /verify?id=QSV-… auto-fills and checks on load.
  useEffect(() => {
    const id = searchParams.get("id");
    if (id) {
      setCode(id);
      runVerify(id);
    }
  }, [searchParams, runVerify]);

  return (
    <div className="mx-auto max-w-2xl space-y-5">
      <Link href="/reports" className="inline-flex items-center gap-1.5 text-sm text-muted-foreground transition-colors hover:text-card-foreground">
        <ArrowLeft className="h-4 w-4" /> Back to Reports
      </Link>

      <PageHeader
        title="Verify Report Authenticity"
        subtitle="Enter (or scan) the Verification ID printed on a report (e.g. QSV-XXXXXXXXXX) to confirm it was genuinely issued by QuickServe and is untampered."
      />

      <Card className="p-5">
        <form onSubmit={(e) => { e.preventDefault(); runVerify(code); }} className="flex flex-col gap-3 sm:flex-row">
          <div className="relative flex-1">
            <Search className="pointer-events-none absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
            <input
              value={code}
              onChange={(e) => setCode(e.target.value)}
              placeholder="QSV-XXXXXXXXXX"
              className="h-11 w-full rounded-xl border border-border bg-muted/40 pl-10 pr-3 font-mono text-sm uppercase text-card-foreground placeholder:font-sans placeholder:normal-case placeholder:text-muted-foreground/70 focus:border-[var(--primary)]/40 focus:outline-none focus:ring-2 focus:ring-[var(--primary)]/20"
            />
          </div>
          <button
            type="submit"
            disabled={checking || !code.trim()}
            className="inline-flex h-11 shrink-0 items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-[var(--accent)] to-[var(--primary)] px-6 text-sm font-semibold text-white shadow-lg shadow-[var(--primary)]/30 transition-transform hover:-translate-y-0.5 disabled:opacity-60"
          >
            {checking ? <Loader2 className="h-4 w-4 animate-spin" /> : <ShieldCheck className="h-4 w-4" />}
            Verify
          </button>
        </form>
      </Card>

      {result?.status === "authentic" && (
        <Card className="border-emerald-500/40 p-5">
          <div className="flex items-center gap-2 text-emerald-400">
            <ShieldCheck className="h-6 w-6" />
            <p className="text-base font-bold">Authentic — genuinely issued by QuickServe</p>
          </div>
          <dl className="mt-4 grid grid-cols-1 gap-x-6 gap-y-3 sm:grid-cols-2">
            {[
              ["Report", result.record.reportName],
              ["Category", result.record.category],
              ["Period", result.record.period],
              ["Records", String(result.record.records)],
              ["Generated", result.record.generatedAt],
              ["Generated by", result.record.generatedBy],
              ["Verification ID", result.record.verifyId],
            ].map(([label, value]) => (
              <div key={label}>
                <dt className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{label}</dt>
                <dd className="mt-0.5 text-sm font-medium text-card-foreground">{value}</dd>
              </div>
            ))}
          </dl>
          <div className="mt-4 rounded-xl border border-dashed border-border bg-muted/30 p-3">
            <p className="text-xs font-medium text-card-foreground">SHA-256 signature</p>
            <p className="mt-1 break-all font-mono text-[10px] text-muted-foreground">{result.record.signature}</p>
          </div>
        </Card>
      )}

      {result?.status === "invalid" && (
        <Card className="border-rose-500/40 p-5">
          <div className="flex items-center gap-2 text-rose-400">
            <ShieldX className="h-6 w-6" />
            <p className="text-base font-bold">Not found</p>
          </div>
          <p className="mt-2 text-sm text-muted-foreground">
            No report was issued with this Verification ID. It may be mistyped, or the document is not an authentic QuickServe report.
          </p>
        </Card>
      )}
    </div>
  );
}

export default function VerifyReportPage() {
  return (
    <Suspense fallback={<div className="mx-auto max-w-2xl p-6 text-sm text-muted-foreground">Loading…</div>}>
      <VerifyInner />
    </Suspense>
  );
}
